#
# Copyright 2020 DXOS.org
#

name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # checkout and install
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd outside-workspace/dependent-package
          yarn install --frozen-lockfile
